supabase_url = "https://pveppzpjsfjyakzxgsze.supabase.co"
supabase_service_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZXBwenBqc2ZqeWFrenhnc3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODM5NjUyMjUsImV4cCI6MTk5OTU0MTIyNX0.91GSQNcXvSFCINAAFCfVjS-fGGCkI_IBtIdVHKvOPJM"
openai_api_key = "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"
